const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('components/ts_webui/web/js/app.js','utf8');
function fn(name){const m=new RegExp('^(?:async )?function '+name+'\\(','m').exec(source);assert(m,name);const text=source.slice(m.index),end=text.indexOf('\n}')+2;assert(end>1);return text.slice(0,end);}
const languages={};for(const lang of ['zh-CN','en-US'])vm.runInNewContext(fs.readFileSync(`components/ts_webui/web/js/lang/${lang}.js`,'utf8'),{i18n:{registerLanguage:(id,data)=>languages[id]=data}});
let locale='zh-CN',writes=[],reject=false,response={code:0,data:{mirror_synced:true}},conditions=[],actions=[];
const nodes=new Map();function el(id){if(!nodes.has(id))nodes.set(id,{value:'',checked:false,disabled:false,dataset:{},style:{},classList:{add(){},remove(){}}});return nodes.get(id);}
const toast=[];const ctx=vm.createContext({console,structuredClone,setTimeout(){},document:{getElementById:el,querySelectorAll:q=>q.includes('condition-row')?conditions:q.includes('action-row')?actions:[],hidden:false},window:{},t:key=>key.split('.').reduce((v,k)=>v?.[k],languages[locale])??key,showToast:(m,k)=>toast.push(m),alert:m=>{throw Error(m)},closeModal(){},refreshRules:async()=>{},refreshAutomationStatus:async()=>{},api:{call:async(method,params)=>{if(method.endsWith('.get'))return {code:0,data:{revision:8}};writes.push({method,params});if(reject)throw Error('synthetic lost reply');return response;}}});
for(const name of ['runtimeText','runtimeSaveError','ruleWriteWithRevision','submitAddRule','toggleManualOnly','quickActionRefreshLog','checkRuleHasNohupSsh'])vm.runInContext(fn(name),ctx);
function row(fields,extra={}){return {...extra,querySelector:s=>fields[s]||null};}
(async()=>{
 for(locale of ['zh-CN','en-US']){
  el('rule-show-dashboard').dataset={};el('rule-allow-manual').dataset={};
  for(const key of ['saved','mirrorWarning','saveUnknown','startBlocked','unknown','revision_conflict','source_read_only'])assert.notEqual(ctx.runtimeText(key),key);
  el('rule-id').value='model';el('rule-name').value='Model';el('rule-logic').value='and';el('rule-cooldown').value='3000';el('rule-revision').value='7';el('rule-manual-only').checked=true;el('rule-enabled').checked=true;el('rule-show-dashboard').checked=false;el('rule-allow-manual').checked=false;
  conditions=[row({'.cond-variable':{value:'upstream.status'},'.cond-operator':{value:'eq'},'.cond-value':{value:'"123"'}},{_originalCondition:{value:'123',value_type:4}})];
  actions=[row({'.action-template-id':{value:'template'},'.action-delay':{value:'12'},'.action-repeat-mode':{value:'count'},'.action-repeat-count':{value:'3'},'.action-repeat-interval':{value:'0'},'.action-has-condition':{checked:false}},{dataset:{},_originalAction:{template_id:'template',type:'cli',command:'synthetic --arg',async:true}})];
  writes=[];await ctx.submitAddRule('model');assert.equal(writes.length,1);const req=writes[0];assert.equal(req.method,'automation.rules.update');assert.equal(req.params.expected_revision,7);assert.equal(req.params.conditions[0].value,'123');assert.equal(req.params.conditions[0].value_type,4);assert.equal(req.params.actions[0].command,'synthetic --arg');assert.equal(req.params.actions[0].async,true);assert.equal(req.params.actions[0].repeat_interval_ms,0);assert.equal(req.params.show_on_dashboard,false);
  response={code:1,message:'revision_conflict'};writes=[];await ctx.submitAddRule('model');assert.equal(writes.length,1);assert.equal(el('rule-name').value,'Model');
  reject=true;writes=[];await ctx.submitAddRule('model');assert.equal(writes.length,1);assert.equal(el('rule-revision').value,'7');assert.equal(el('rule-revision').dataset.observedRevision,8);assert.equal(el('add-rule-modal').dataset.saving,'false');reject=false;response={code:0,data:{mirror_synced:true}};
  el('rule-show-dashboard').dataset.present='false';writes=[];await ctx.submitAddRule('model');assert(!Object.hasOwn(writes[0].params,'show_on_dashboard'));el('rule-show-dashboard').dataset.dirty='true';writes=[];await ctx.submitAddRule('model');assert.equal(writes[0].params.show_on_dashboard,false);
 }
 const log=el('quick-log-content');log.isConnected=true;log.dataset={};ctx.window._sshHostsData={host:{host:'192.0.2.8',username:'test'}};vm.runInContext("let quickActionLastContent=''; let sshCommands={host:[{id:'new',name:'model',command:'true',nohup:true,serviceMode:true}]};",ctx);
 let resolve,reads=0;ctx.api.call=()=>{reads++;return new Promise(r=>resolve=r)};const pending=ctx.quickActionRefreshLog('/tmp/test.log','host');await ctx.quickActionRefreshLog('/tmp/test.log','host');assert.equal(reads,1);log.isConnected=false;resolve({code:0,data:{stdout:'obsolete'}});await pending;assert.notEqual(log.textContent,'obsolete');assert.equal(log.dataset.loading,'false');
 ctx.api.call=async method=>method==='automation.rules.get'?{code:0,data:{actions:[{type:'ssh_cmd_ref',cmd_id:'old',template_id:'template'}]}}:{code:0,data:{type:'ssh_cmd_ref',ssh_ref:{cmd_id:'new'}}};assert.equal((await ctx.checkRuleHasNohupSsh({id:'rule',actions_count:1})).commandId,'new');ctx.api.call=async method=>method==='automation.rules.get'?{code:0,data:{actions:[{type:'ssh_cmd_ref',cmd_id:'missing'}]}}:{code:1};assert.equal((await ctx.checkRuleHasNohupSsh({id:'rule',actions_count:1})).unresolved,true);ctx.api.call=async()=>({code:1});assert.equal((await ctx.checkRuleHasNohupSsh({id:'rule',actions_count:1})).unresolved,true);
 const card={dataset:{}};const statusValue={};const statusContainer={isConnected:true,dataset:{command:'model'},closest:()=>card,querySelector:()=>statusValue};
 ctx.document.hidden=false;ctx.document.querySelectorAll=()=>[statusContainer];
 vm.runInContext('let serviceStatusInFlight=false;',ctx);vm.runInContext(fn('updateQuickActionServiceStatus'),ctx);
 let statusReads=0;ctx.api.call=async(method,params)=>{assert.equal(method,'automation.services.status');assert.equal(params.verify,undefined);statusReads++;return {code:0,data:{state:'unknown',source:'none'}};};
 for(let i=0;i<3;i++)await ctx.updateQuickActionServiceStatus();assert.equal(statusReads,3);
 console.log('PASS actual UI functions: bilingual states, one revisioned update, manual conditions/types, inline fields/repeat preservation, explicit false vs omitted, conflict/draft/uncertain write');
})().catch(e=>{console.error(e);process.exitCode=1});
